### ISSUE TITLE
Test the planner + mostly focus on offensive subtasks

### ISSUE THREAD

**Issue by filipendo125** [Ramsey144/SDP-2016-9E#66]
Test various cases of currently implemented subtasks. Optionally, write a requirements file / list for each. To launch tests, enter 'custom' and the (string) next to the following values.
- [ ] acquire ball (acq)
- [ ] shoot (shoot)
- [ ] defend penalty (defpen)
- [ ] kick off (kickoff)
- [ ] align with ball (algnball)
- [ ] defend goal from ball (defgoal)
- [ ] turn to ally (lickally)
- [ ] pass (pass)
- [ ] panic shoot (panshoot)
- [ ] defend enemy shot (defshot)
- [ ] move to receive pass (moverec)
- [ ] intercept shot (intrcshot)
- [ ] intercept pass (intrcpass)
- [ ] receive pass (recpass)
- [ ] More?
